{
  "comments": [
    {
      "key": {
        "uuid": "1d877f0d_c3d10a0f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 1119600
      },
      "writtenOn": "2020-09-21T11:23:00Z",
      "side": 1,
      "message": "The crash in the failing bot run looks related. Do we understand why it is crashing?",
      "revId": "07adff47df504c678cdcd371907f9b5df4ac9944",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}