{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1be86f26_e6b7e80d",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1396442
      },
      "writtenOn": "2023-03-03T10:57:36Z",
      "side": 1,
      "message": "PTanotherLook, I have also added in the reset() of the trace model which seems to fix the layout test failures (although I am not entirely sure why...)",
      "revId": "49f3366a88dd4ed53b5d37ec6e58a6a6b9e088a0",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}