{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "3f843c6c_fca45af5",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1323977
      },
      "writtenOn": "2024-05-29T05:08:53Z",
      "side": 1,
      "message": "Philip, is this something we want to do? Failing after hooks still hint at problems. The unit tests\u0027 async instrumentation will report any problems in the after hook as well (IIRC).",
      "revId": "a20d4d712bef75133c1a1881320292f8ddaf98f2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "85d2d917_142bd1bd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1372423
      },
      "writtenOn": "2024-05-29T07:02:41Z",
      "side": 1,
      "message": "@liviurau@google.com Do you have examples for after-hook failures that aren\u0027t actionable?\n\nI think I agree wis Simon, while I get that such failures aren\u0027t exonorable, there\u0027s still value in reporting to rdb, for instance for luci analysis.",
      "parentUuid": "3f843c6c_fca45af5",
      "revId": "a20d4d712bef75133c1a1881320292f8ddaf98f2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "364710d2_72a0847b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1368735
      },
      "writtenOn": "2024-05-29T07:44:39Z",
      "side": 1,
      "message": "Sure: https://ci.chromium.org/ui/p/devtools-frontend/builders/ci/Stand-alone%20Win/12468/test-results?sortby\u003d\u0026groupby\u003d . \n\nThere is bug in the exoneration procedure that will consider everything to be be fine just because the exoneration run did not fail. This is wrong because need to make sure that we did manage to run the tests that failed and it happened that we actually did not run anything in some case (grep mismatches). \n\nOnce we fix the bug by querying rbd for final test results that \u0027after\u0027 hook will only show as failed. \n\nAs a bit of extra context a hook gets reported to rdb only in case of a failure. \n\nSo an exoneration run will simply not report the hook as passing even if it does.",
      "parentUuid": "85d2d917_142bd1bd",
      "revId": "a20d4d712bef75133c1a1881320292f8ddaf98f2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7c11e34d_d5ca1a47",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1368735
      },
      "writtenOn": "2024-05-29T07:52:58Z",
      "side": 1,
      "message": "Another note: the exoneration attempt on the above failure runs with a grep for the hook now. That effectively fails to run any tests. Command: \n```\nrdb stream -tag test_type:e2e_tests -coerce-negative-duration \n-exonerate-unexpected-pass -inherit-sources -baseline-id ci:Stand-alone Win \n-- vpython3 -u third_party\\node\\node.py --output out/Release/gen/test/run.js \n--artifacts-dir\u003d${ISOLATED_OUTDIR} --skip-ninja --coverage \n--grep\u003d\"afterAll in \"{root}\"\" test/e2e\n```\nhttps://chromium-swarm.appspot.com/task?d\u003dtrue\u0026id\u003d69d664d1d6aa8310",
      "parentUuid": "364710d2_72a0847b",
      "revId": "a20d4d712bef75133c1a1881320292f8ddaf98f2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "616c76d3_c3ca4bfa",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1368735
      },
      "writtenOn": "2024-05-29T07:59:49Z",
      "side": 1,
      "message": "In my opinion the after hooks can be ignored",
      "parentUuid": "7c11e34d_d5ca1a47",
      "revId": "a20d4d712bef75133c1a1881320292f8ddaf98f2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c8b601ba_11b9d213",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 1372423
      },
      "writtenOn": "2024-05-29T08:01:35Z",
      "side": 1,
      "message": "Can we maybe find a way to ignore them for exoneration? or possibly fail exoneration in general if no test ran?",
      "parentUuid": "616c76d3_c3ca4bfa",
      "revId": "a20d4d712bef75133c1a1881320292f8ddaf98f2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}