{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "7f45dc76_dc55a35b",
        "filename": "front_end/core/sdk/DebuggerModel.ts",
        "patchSetId": 6
      },
      "lineNbr": 1460,
      "author": {
        "id": 1372423
      },
      "writtenOn": "2024-07-19T12:51:21Z",
      "side": 1,
      "message": "What happens with a wasm exception? Wouldn\u0027t we want to show that, too?",
      "revId": "e08dab550a2d42d00261e16398aef0586a71bd31",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "66c5b524_d169c958",
        "filename": "front_end/core/sdk/DebuggerModel.ts",
        "patchSetId": 6
      },
      "lineNbr": 1460,
      "author": {
        "id": 1323977
      },
      "writtenOn": "2024-07-19T15:48:52Z",
      "side": 1,
      "message": "I just ported the existing code modulo limiting \"Exception\" to the top-most frame. Also we don\u0027t have \"break on exception\" for wasm (for now), so nothing would show up in any case.",
      "parentUuid": "7f45dc76_dc55a35b",
      "revId": "e08dab550a2d42d00261e16398aef0586a71bd31",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}